apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    app: tomcat
 spec:
      containers:
      - name: tomcat
        image: vairam86/demodocker:imagetagversion
        ports:
         - containerPort: 8080